name: Android CI-CD
on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version : '17'
          distribution : 'adopt'

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: lint-Report
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version : '17'
          distribution : 'adopt'

      - name: Run Lint
        run: ./gradlew test

      - name: Upload a Unit Test Report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: unit-tests-report
          path: app/build/reports/tests/testDebugUnitTest/
          
          
  build-apk:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version : '17'
          distribution : 'adopt'

      - name: Build with gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Apk
          path: app/build/outputs/apk/debug/app-debug.apk
