name: Android CI-CD
on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: lint-Report
          path: app/build/reports/lint-results-debug.html
